name: Lint Package JSON

on:
  push:
    paths:
      - 'package.json'
  pull_request:
    paths:
      - 'package.json'

jobs:
  lint_package_json:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
      
      - name: Check "files" key in package.json
        run: |
          PACKAGE_JSON=$(cat package.json)
          if echo "$PACKAGE_JSON" | jq 'has("files")' | grep -q 'true'; then
            echo "The 'files' key is present in package.json"
          else
            echo "Error: The 'files' key is missing in package.json" >&2
            exit 1
          fi
      - name: Lint package.json (no production dependencies allowed)
        run: |
          BASE_PACKAGE=$(git show origin/main:package.json)
          echo "$BASE_PACKAGE" > base_package.json
          npx json-diff base_package.json package.json | grep -q 'dependencies' || echo "No new production dependencies detected."